# Generated by Django 5.0.2 on 2024-02-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_description', models.CharField(max_length=200)),
                ('movie_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='students_model',
            name='student_Roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
