# Generated by Django 5.0.2 on 2024-02-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_movies_model_alter_students_model_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies_model',
            name='movie_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
