# Generated by Django 5.0.3 on 2024-03-28 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.domain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('task_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('task_description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('P', 'Pending'), ('M', 'Miseed'), ('C', 'Complete')], default='A', max_length=1)),
                ('Assigned_time', models.DateTimeField(auto_now_add=True)),
                ('to_which_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.userprofileinfo')),
            ],
        ),
    ]
